name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull golang

      - name: Get source
        uses: actions/checkout@v3
      - name: Build container with Podman
        run: |
          ls
          podman build -t vana -f DockerFile .
